@startuml

package "erizo"
{
    enum HandlerDir
    {
        IN,
        OUT,
        BOTH
    }

    class ContextImpl<<H>>
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    class HandlerContext
    {

    }

    abstract class InboundLink
    {
        virtual void read(std::shared_ptr<DataPacket> packet) = 0;
        virtual void readEOF() = 0;
        virtual void transportActive() = 0;
        virtual void transportInactive() = 0;
    }

    abstract class OutboundLink
    {

    }

    class ContextImplBase<<Handler,HandlerContext>>
    {
        Context* impl_;
        std::weak_ptr<PipelineBase> pipelineWeak_;
        PipelineBase* pipelineRaw_;
        std::shared_ptr<H> handler_;
        InboundLink* nextIn_;
        OutboundLink* nextOut_;
        bool attached_;
        void initialize()
    }

    abstract class PipelineContext
    {

    }

    class InboundContextImpl
    {
        HandlerDir dir = HandlerDir::IN;
        void read(std::shared_ptr<DataPacket> packet) override
    }

    abstract class InboundHandlerContext
    {
        virtual void fireRead(std::shared_ptr<DataPacket> packet) = 0;
        virtual void fireReadEOF() = 0;
        virtual void fireTransportActive() = 0;
        virtual void fireTransportInactive() = 0;
        virtual PipelineBase* getPipeline() = 0;
        virtual std::shared_ptr<PipelineBase> getPipelineShared() = 0;
    }

    abstract class OutboundContextImpl
    {
        HandlerDir dir = HandlerDir::OUT;
    }
    
    class OutboundHandlerContext
    {

    }

    PipelineContext <|-- ContextImplBase
    InboundLink <|-- ContextImpl
    OutboundLink <|-- ContextImpl
    ContextImplBase <|-- ContextImpl
    HandlerContext <|-- ContextImpl

    InboundLink <|-- InboundContextImpl
    InboundHandlerContext <|-- InboundContextImpl
    ContextImplBase <|-- InboundContextImpl

    OutboundLink <|-- OutboundContextImpl
    OutboundHandlerContext <|-- OutboundContextImpl
    ContextImplBase <|-- OutboundContextImpl

    HandlerDir --o ContextImpl
    HandlerDir --o InboundContextImpl
    HandlerDir --o OutboundContextImpl

    class HandlerBase<<InboundHandlerContext>>
    {

    }

    class InboundHandler
    {
        HandlerDir dir = HandlerDir::IN
    }

    HandlerBase <|-- InboundHandler
    HandlerBase --o InboundHandlerContext

    class PacketReader
    {
        HandlerDir dir = HandlerDir::IN
    }

    InboundHandler <|-- PacketReader

    class Handler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    class RtcpProcessorHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- RtcpProcessorHandler

    class OutboundHandler
    {
        HandlerDir dir = HandlerDir::OUT
    }

    class FecReceiverHandler
    {
        HandlerDir dir = HandlerDir::OUT
    }

    OutboundHandler <|-- FecReceiverHandler

    class LayerBitrateCalculationHandler
    {
        HandlerDir dir = HandlerDir::OUT
    }

    OutboundHandler <|-- LayerBitrateCalculationHandler


    class QualityFilterHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- QualityFilterHandler

    class IncomingStatsHandler
    {
        HandlerDir dir = HandlerDir::IN
    }

    InboundHandler <|-- IncomingStatsHandler

    class FakeKeyframeGeneratorHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- FakeKeyframeGeneratorHandler

    class RtpTrackMuteHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- RtpTrackMuteHandler

    class RtpSlideShowHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- RtpSlideShowHandler

    class RtpPaddingGeneratorHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- RtpPaddingGeneratorHandler

    class PeriodicPliHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- PeriodicPliHandler

    class PliPriorityHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- PliPriorityHandler

    class PliPacerHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- PliPacerHandler

    class RtpPaddingRemovalHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- RtpPaddingRemovalHandler

    class BandwidthEstimationHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- BandwidthEstimationHandler

    class RtcpFeedbackGenerationHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- RtcpFeedbackGenerationHandler

    class RtpRetransmissionHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- RtpRetransmissionHandler
    
    class SRPacketHandler
    {
        HandlerDir dir = HandlerDir::BOTH
    }

    Handler <|-- SRPacketHandler

    class LayerDetectorHandler
    {
        HandlerDir dir = HandlerDir::IN
    }

    InboundHandler <|-- LayerDetectorHandler

    class OutgoingStatsHandler
    {
        HandlerDir dir = HandlerDir::OUT
    }

    OutboundHandler <|-- OutgoingStatsHandler

    class PacketCodecParser
    {
        HandlerDir dir = HandlerDir::IN
    }

    InboundHandler <|-- PacketCodecParser

    class PacketWriter
    {
        HandlerDir dir = HandlerDir::OUT
    }

    OutboundHandler <|-- PacketWriter

    RtcpProcessorHandler --> PacketReader : in >
    LayerBitrateCalculationHandler --> RtcpProcessorHandler : in >
    QualityFilterHandler --> LayerBitrateCalculationHandler : in/out >
    IncomingStatsHandler --> QualityFilterHandler : in >
    FakeKeyframeGeneratorHandler --> IncomingStatsHandler : in >
    RtpTrackMuteHandler --> FakeKeyframeGeneratorHandler : in/out >
    RtpSlideShowHandler --> RtpTrackMuteHandler : in/out >
    RtpPaddingGeneratorHandler --> RtpSlideShowHandler : in/out >
    PeriodicPliHandler --> RtpPaddingGeneratorHandler : in/out >
    PliPriorityHandler --> PeriodicPliHandler : in/out >
    PliPacerHandler --> PliPriorityHandler : in/out >
    RtpPaddingRemovalHandler --> PliPacerHandler : in/out >
    BandwidthEstimationHandler --> RtpPaddingRemovalHandler : in/out >
    RtcpFeedbackGenerationHandler --> BandwidthEstimationHandler : in/out >
    RtpRetransmissionHandler --> RtcpFeedbackGenerationHandler : in/out >
    SRPacketHandler --> RtpRetransmissionHandler : in/out >
    LayerDetectorHandler --> SRPacketHandler : in >
    PacketCodecParser --> LayerDetectorHandler : in start >



    FecReceiverHandler --> RtcpProcessorHandler : out >
    LayerBitrateCalculationHandler --> FecReceiverHandler : out >
    FakeKeyframeGeneratorHandler --> QualityFilterHandler : out >
    OutgoingStatsHandler --> SRPacketHandler : out >
    PacketWriter --> OutgoingStatsHandler : out start >




    class ServiceContextImpl<<Service>>
    {

    }



    class ServiceContext
    {

    }

    class ServiceContextImplBase<<Service,ServiceContext>>
    {

    }

    ServiceContext <|-- ServiceContextImpl
    ServiceContextImplBase <|-- ServiceContextImpl

    class PipelineServiceContext
    {

    }

    PipelineServiceContext <|-- ServiceContextImplBase

    class PipelineBase
    {
        void addService()
        void addFront()
        void finalize()
        vector<PipelineServiceContext> service_ctxs_
        vector<std::shared_ptr<PipelineContext>> ctxs_
        vector<PipelineContext*> inCtxs_
        vector<PipelineContext*> outCtxs_
    }
    note left
    addService 
    add ServiceContextImpl 
    to service_ctxs    
    end note 

    note right
    addFront 
    add ContextImpl
    to inCtxs_ or outCtxs_ depend on HandlerDir
    end note 

    ServiceContextImpl --o PipelineBase


    class Pipeline
    {
        void finalize()
    }

    PipelineBase <|-- Pipeline 


    class MediaStream
    {
        Pipeline _pipeline
    }

    Pipeline --* MediaStream

}

@enduml
