@startuml

package webrtc
{
    class EncodedImageCallback
    {
        void OnEncodedImage();
    }

    abstract class RtpVideoSenderInterface 
    {
        void OnEncodedImage();
    }

    EncodedImageCallback <|-- RtpVideoSenderInterface

    class RTPSenderVideo
    {
        RTPSender*          rtp_sender_
        SendEncodedImage();
        SendVideo();
        LogAndSendToNetwork();
    }

    abstract class RtpPacketSender
    {
        EnqueuePackets();
    }

    class RtpPacketHistory
    {

    }

    abstract class TransportFeedbackObserver
    {
        void OnAddPacket();
        void OnTransportFeedback();
    }

    class RtpSenderEgress
    {
        RtpPacketHistory*          rtp_packet_history;虽然没有平滑，但是为了nack还是保存
        以下两个通过构造函数传入依赖
        TransportFeedbackObserver* feed_back;
        Transport*                 transport_;真实发送数据接口
        AddPacketToTransportFeedback();
    }

    RtpPacketHistory --* RtpSenderEgress  

    class NonPacedPacketSender
    {
        uint16_t transport_sequence_number_;
        RtpSenderEgress*        sender;
        EnqueuePackets();
        PrepareForSend();自增transport序列号
    }

    RtpSenderEgress --* NonPacedPacketSender

    class PacketSender
    {
        SendPacket();
    }

    class PacketRouter
    {
        map<uint32_t, RtpRtcpInterface*>  send_modules_map_
        uint16_t            transport_seq_;
        SendPacket(); 做序列号的递增
        AddSendRtpModuleToMap();
    }

    ModuleRtpRtcpImpl2 --* PacketRouter

    PacketSender <|-- PacketRouter

    class PacingController
    {
        PacketSender*       packet_sender;PaceSender 构造时候传入的packetRouter
        PacketQueue         packet_queue;
        EnqueuePacket();
        ProcessPacket();
        GetPendingPacket();
    }

    class Module
    {
        process();
    }

    class PacedSender
    {
        PacketRouter*           packet_router;
        PacingController        pacing_controller;
        EnqueuePackets();
        process(); 调用controller 的ProcessPacket
    }

    PacketRouter --* PacedSender
    Module <|-- PacedSender

    PacingController --* PacedSender
    PacketSender --* PacingController

    RtpPacketSender <|-- PacedSender
    RtpPacketSender <|-- NonPacedPacketSender

    class RTPSender
    {
        RtpPacketSender*      paced_sender_;  
        EnqueuePackets();
    }

    RtpPacketSender --* RTPSender

    class RtpSenderContext
    {
        RtpPacketHistory packet_history;
        RtpSenderEgress packet_sender;
        RtpSenderEgress::NonPacedPacketSender non_paced_sender;
        RTPSender packet_generator; 三元组生成
    }

    RtpPacketHistory --* RtpSenderContext  

    RTPSender --* RTPSenderVideo

    RtpSenderEgress --* RtpSenderContext

    RTPSender --* RtpSenderContext

    abstract class RtpRtcpInterface
    {
        void trySendPacket();
    }

    class ModuleRtpRtcpImpl2
    {
        RtpSenderContext*                  rtp_sender;
        void trySendPacket(); 调用rtp_sender 的rtpSenderEgress 发送
        OnPacketsAcknowledged(vector<int> sequence_numbers);收到数据包ack 进行清除
    }

    RtpRtcpInterface <|-- ModuleRtpRtcpImpl2

    RtpSenderContext --* ModuleRtpRtcpImpl2

    class RtpStreamSender
    {
        ModuleRtpRtcpImpl2*         rtp_rtcp;
        RTPSenderVideo*             sender_video;
        VideoFecGenerator*          fec_generator;
    }

    ModuleRtpRtcpImpl2 --* RtpStreamSender
    RTPSenderVideo --* RtpStreamSender

    abstract class StreamFeedbackObserver
    {
        void OnPacketFeedbackVector();
    }

    class RtpVideoSender
    {
        将生成的rtpmodule 注册在PacketRouter 中
        将自己注册到TransportFeedbackDemuxer 中，后续feedback 过来处理
        RtpVideoSender();
        OnEncodedImage(); RtpStreamSender->sender_video
        std::vector<RtpStreamSender> CreateRtpStreamSenders(); 全局函数，但是影响该类
        vector<RtpStreamSender> *rtp_streams;
        OnPacketFeedbackVector();
    }
    
    StreamFeedbackObserver <|-- RtpVideoSender
    RtpStreamSender --* RtpVideoSender
    RtpVideoSender -- PacketRouter
    RtpVideoSenderInterface <|-- RtpVideoSender

    abstract class RtpTransportControllerSendInterface
    {
        TransportFeedbackObserver* transport_feedback_observer();
        RtpVideoSenderInterface* CreateRtpVideoSender();
    }

    class TransportFeedbackDemuxer
    {
        OnAddPacket();handle
        OnTransportFeedback();handle
    }

    class RtpTransportControllerSend
    {
        TransportFeedbackDemuxer feedback_demuxer;
        RtpVideoSenderInterface* CreateRtpVideoSender();
        void OnAddPacket();
        void OnTransportFeedback();
    }

    TransportFeedbackDemuxer --* RtpTransportControllerSend
    RtpTransportControllerSendInterface <|-- RtpTransportControllerSend
    TransportFeedbackObserver <|-- RtpTransportControllerSend

    package Video 
    {
        class EncoderSink
        {

        }

        EncodedImageCallback <|-- EncoderSink

        class VideoSendStreamImpl
        {
            void OnEncodedImage();
            RtpVideoSenderInterface* rtp_video_sender;
            RtpTransportControllerSendInterface* transport;
        }
        RtpTransportControllerSendInterface --* VideoSendStreamImpl
        EncoderSink <|-- VideoSendStreamImpl
        RtpVideoSenderInterface --* VideoSendStreamImpl

        class VideoSendStream 
        {
            VideoSendStreamImpl* send_stream_;
        }

        VideoSendStreamImpl --* VideoSendStream
    }

    class Call 
    {
        RtpTransportControllerSendInterface* transport_send_ptr_;
    }

    RtpTransportControllerSendInterface --* Call
}


@enduml
